[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "5000"
DEBUG = "False"

